# Generated by Django 5.0.1 on 2024-05-04 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_creates',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
