# Generated by Django 5.0.1 on 2024-05-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_creates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_creates',
            new_name='date_created',
        ),
    ]
